// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Chart1;
extern lv_obj_t *ui_adc0Text;
extern lv_obj_t *ui_adc0Value;
extern lv_obj_t *ui_adc1Text;
extern lv_obj_t *ui_adc1Value;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

