// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_Screen2 = NULL;lv_obj_t *ui_Image2 = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_Label6 = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image2 = lv_img_create(ui_Screen2);
lv_obj_set_width( ui_Image2, 129);
lv_obj_set_height( ui_Image2, 72);
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label4, 172);
lv_obj_set_height( ui_Label4, 1);
lv_obj_set_x( ui_Label4, 0 );
lv_obj_set_y( ui_Label4, -43 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"");
lv_obj_set_style_bg_color(ui_Label4, lv_color_hex(0xABA0A0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_Screen2);
lv_obj_set_width( ui_Label6, 172);
lv_obj_set_height( ui_Label6, 1);
lv_obj_set_x( ui_Label6, 0 );
lv_obj_set_y( ui_Label6, 41 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"");
lv_obj_set_style_bg_color(ui_Label6, lv_color_hex(0xA79DA0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen2_screen_destroy(void)
{
   if (ui_Screen2) lv_obj_del(ui_Screen2);

// NULL screen variables
ui_Screen2= NULL;
ui_Image2= NULL;
ui_Label4= NULL;
ui_Label6= NULL;

}
