// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_Chart1 = NULL;lv_obj_t *ui_adc0Text = NULL;lv_obj_t *ui_adc0Value = NULL;lv_obj_t *ui_adc1Text = NULL;lv_obj_t *ui_adc1Value = NULL;lv_obj_t *ui_Label10 = NULL;lv_obj_t *ui_Label11 = NULL;lv_obj_t *ui_Label12 = NULL;lv_obj_t *ui_Label13 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_Label3 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_Screen1, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xF809E0), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 2 );
lv_obj_set_y( ui_Label5, -38 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"last 10 samples");

ui_Chart1 = lv_chart_create(ui_Screen1);
lv_obj_set_width( ui_Chart1, 152);
lv_obj_set_height( ui_Chart1, 90);
lv_obj_set_x( ui_Chart1, 1 );
lv_obj_set_y( ui_Chart1, -92 );
lv_obj_set_align( ui_Chart1, LV_ALIGN_CENTER );
lv_chart_set_type( ui_Chart1, LV_CHART_TYPE_LINE);
lv_chart_set_range( ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 4096);
lv_chart_set_range( ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 4096);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 0, false, 50);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 0, 0, false, 25);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 0, 0, false, 25);

ui_adc0Text = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_adc0Text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_adc0Text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_adc0Text, -60 );
lv_obj_set_y( ui_adc0Text, 0 );
lv_obj_set_align( ui_adc0Text, LV_ALIGN_CENTER );
lv_label_set_text(ui_adc0Text,"ADC0");

ui_adc0Value = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_adc0Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_adc0Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_adc0Value, -20 );
lv_obj_set_y( ui_adc0Value, 0 );
lv_obj_set_align( ui_adc0Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_adc0Value,"0");

ui_adc1Text = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_adc1Text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_adc1Text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_adc1Text, -60 );
lv_obj_set_y( ui_adc1Text, 20 );
lv_obj_set_align( ui_adc1Text, LV_ALIGN_CENTER );
lv_label_set_text(ui_adc1Text,"ADC1");

ui_adc1Value = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_adc1Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_adc1Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_adc1Value, -20 );
lv_obj_set_y( ui_adc1Value, 20 );
lv_obj_set_align( ui_adc1Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_adc1Value,"0");

ui_Label10 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label10, 60);
lv_obj_set_height( ui_Label10, 40);
lv_obj_set_x( ui_Label10, -42 );
lv_obj_set_y( ui_Label10, 129 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"0");
lv_obj_set_style_text_align(ui_Label10, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Label10, lv_color_hex(0xF407D3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label11 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label11, 60);
lv_obj_set_height( ui_Label11, 40);
lv_obj_set_x( ui_Label11, -42 );
lv_obj_set_y( ui_Label11, 76 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"0xABCD\n0xFFFF");
lv_obj_set_style_text_align(ui_Label11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Label11, lv_color_hex(0x2C71EF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label12 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label12, 60);
lv_obj_set_height( ui_Label12, 40);
lv_obj_set_x( ui_Label12, 38 );
lv_obj_set_y( ui_Label12, 129 );
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"OFF");
lv_obj_set_style_text_align(ui_Label12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Label12, lv_color_hex(0x7F7F37), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label13 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label13, 60);
lv_obj_set_height( ui_Label13, 40);
lv_obj_set_x( ui_Label13, 38 );
lv_obj_set_y( ui_Label13, 76 );
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"ON");
lv_obj_set_style_text_align(ui_Label13, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Label13, lv_color_hex(0xF7A732), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, 30);
lv_obj_set_height( ui_Label1, -2);
lv_obj_set_x( ui_Label1, 49 );
lv_obj_set_y( ui_Label1, 126 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"");
lv_obj_set_style_bg_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 0 );
lv_obj_set_y( ui_Label2, -150 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"ADC 0");

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 42 );
lv_obj_set_y( ui_Label3, 15 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"multi line\ntext\ntest\ntest2");
lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Label5= NULL;
ui_Chart1= NULL;
ui_adc0Text= NULL;
ui_adc0Value= NULL;
ui_adc1Text= NULL;
ui_adc1Value= NULL;
ui_Label10= NULL;
ui_Label11= NULL;
ui_Label12= NULL;
ui_Label13= NULL;
ui_Label1= NULL;
ui_Label2= NULL;
ui_Label3= NULL;

}
