// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: DCF77

#include "../ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_lblProjectDesc = NULL;lv_obj_t *ui_lblTimeHours = NULL;lv_obj_t *ui_lblTimeColon = NULL;lv_obj_t *ui_lblTimeMinutes = NULL;lv_obj_t *ui_lblDate = NULL;lv_obj_t *ui_lblTimeLastDecode = NULL;lv_obj_t *ui_lblTimeZone = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_Label8 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_Label9 = NULL;lv_obj_t *ui_imgAntenna = NULL;lv_obj_t *ui_barSignalStrength = NULL;lv_obj_t *ui_lblPar1 = NULL;lv_obj_t *ui_lblPar2 = NULL;lv_obj_t *ui_lblPar3 = NULL;lv_obj_t *ui_Label1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_lblProjectDesc = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lblProjectDesc, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblProjectDesc, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblProjectDesc, -80 );
lv_obj_set_y( ui_lblProjectDesc, -74 );
lv_obj_set_align( ui_lblProjectDesc, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblProjectDesc,"DCF77 receiver");
lv_obj_set_style_text_color(ui_lblProjectDesc, lv_color_hex(0x890BFA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblProjectDesc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_lblProjectDesc, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblTimeHours = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lblTimeHours, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblTimeHours, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblTimeHours, -22 );
lv_obj_set_y( ui_lblTimeHours, -16 );
lv_obj_set_align( ui_lblTimeHours, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblTimeHours,"10");
lv_obj_set_style_text_font(ui_lblTimeHours, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblTimeColon = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lblTimeColon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblTimeColon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblTimeColon, 10 );
lv_obj_set_y( ui_lblTimeColon, -16 );
lv_obj_set_align( ui_lblTimeColon, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblTimeColon,":");
lv_obj_set_style_text_font(ui_lblTimeColon, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblTimeMinutes = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lblTimeMinutes, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblTimeMinutes, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblTimeMinutes, 47 );
lv_obj_set_y( ui_lblTimeMinutes, -16 );
lv_obj_set_align( ui_lblTimeMinutes, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblTimeMinutes,"45");
lv_obj_set_style_text_font(ui_lblTimeMinutes, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblDate = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lblDate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblDate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblDate, 13 );
lv_obj_set_y( ui_lblDate, 28 );
lv_obj_set_align( ui_lblDate, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblDate,"Mon 11/12 2025");
lv_obj_set_style_text_font(ui_lblDate, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblTimeLastDecode = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lblTimeLastDecode, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblTimeLastDecode, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblTimeLastDecode, -15 );
lv_obj_set_y( ui_lblTimeLastDecode, 74 );
lv_obj_set_align( ui_lblTimeLastDecode, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblTimeLastDecode,"11/12 2025 9:01");
lv_obj_set_style_text_color(ui_lblTimeLastDecode, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblTimeLastDecode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblTimeZone = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lblTimeZone, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lblTimeZone, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_lblTimeZone, -103 );
lv_obj_set_y( ui_lblTimeZone, 16 );
lv_obj_set_align( ui_lblTimeZone, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblTimeZone,"CEST");
lv_obj_set_style_text_color(ui_lblTimeZone, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_lblTimeZone, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, -114 );
lv_obj_set_y( ui_Label6, 74 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"last decode");
lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label8, 30);
lv_obj_set_height( ui_Label8, 15);
lv_obj_set_x( ui_Label8, -143 );
lv_obj_set_y( ui_Label8, -30 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"CB");
lv_obj_set_style_bg_color(ui_Label8, lv_color_hex(0xCFD006), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, 30);
lv_obj_set_height( ui_Label2, 15);
lv_obj_set_x( ui_Label2, -143 );
lv_obj_set_y( ui_Label2, -8 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"ST");
lv_obj_set_style_bg_color(ui_Label2, lv_color_hex(0xFA068A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label7, 30);
lv_obj_set_height( ui_Label7, 15);
lv_obj_set_x( ui_Label7, -143 );
lv_obj_set_y( ui_Label7, 14 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"TZ");
lv_obj_set_style_bg_color(ui_Label7, lv_color_hex(0x0670FA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label9, 30);
lv_obj_set_height( ui_Label9, 15);
lv_obj_set_x( ui_Label9, -143 );
lv_obj_set_y( ui_Label9, 36 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"PAR");
lv_obj_set_style_bg_color(ui_Label9, lv_color_hex(0x08A548), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_imgAntenna = lv_img_create(ui_Screen1);
lv_img_set_src(ui_imgAntenna, &ui_img_wifi_png);
lv_obj_set_width( ui_imgAntenna, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_imgAntenna, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_imgAntenna, 138 );
lv_obj_set_y( ui_imgAntenna, -64 );
lv_obj_set_align( ui_imgAntenna, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imgAntenna, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgAntenna, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_barSignalStrength = lv_bar_create(ui_Screen1);
lv_bar_set_value(ui_barSignalStrength,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_barSignalStrength, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_barSignalStrength, 10);
lv_obj_set_height( ui_barSignalStrength, 100);
lv_obj_set_x( ui_barSignalStrength, 138 );
lv_obj_set_y( ui_barSignalStrength, 10 );
lv_obj_set_align( ui_barSignalStrength, LV_ALIGN_CENTER );

ui_lblPar1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lblPar1, 10);
lv_obj_set_height( ui_lblPar1, 10);
lv_obj_set_x( ui_lblPar1, -116 );
lv_obj_set_y( ui_lblPar1, 37 );
lv_obj_set_align( ui_lblPar1, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblPar1,"");
lv_obj_set_style_bg_color(ui_lblPar1, lv_color_hex(0x05F93E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblPar1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblPar2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lblPar2, 10);
lv_obj_set_height( ui_lblPar2, 10);
lv_obj_set_x( ui_lblPar2, -100 );
lv_obj_set_y( ui_lblPar2, 37 );
lv_obj_set_align( ui_lblPar2, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblPar2,"");
lv_obj_set_style_bg_color(ui_lblPar2, lv_color_hex(0xF90524), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblPar2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lblPar3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_lblPar3, 10);
lv_obj_set_height( ui_lblPar3, 10);
lv_obj_set_x( ui_lblPar3, -84 );
lv_obj_set_y( ui_lblPar3, 37 );
lv_obj_set_align( ui_lblPar3, LV_ALIGN_CENTER );
lv_label_set_text(ui_lblPar3,"");
lv_obj_set_style_bg_color(ui_lblPar3, lv_color_hex(0x05F93E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_lblPar3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, 30);
lv_obj_set_height( ui_Label1, 15);
lv_obj_set_x( ui_Label1, -105 );
lv_obj_set_y( ui_Label1, -8 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"LS");
lv_obj_set_style_bg_color(ui_Label1, lv_color_hex(0xFA068A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_lblProjectDesc= NULL;
ui_lblTimeHours= NULL;
ui_lblTimeColon= NULL;
ui_lblTimeMinutes= NULL;
ui_lblDate= NULL;
ui_lblTimeLastDecode= NULL;
ui_lblTimeZone= NULL;
ui_Label6= NULL;
ui_Label8= NULL;
ui_Label2= NULL;
ui_Label7= NULL;
ui_Label9= NULL;
ui_imgAntenna= NULL;
ui_barSignalStrength= NULL;
ui_lblPar1= NULL;
ui_lblPar2= NULL;
ui_lblPar3= NULL;
ui_Label1= NULL;

}
