// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: DCF77

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_lblProjectDesc;
extern lv_obj_t *ui_lblTimeHours;
extern lv_obj_t *ui_lblTimeColon;
extern lv_obj_t *ui_lblTimeMinutes;
extern lv_obj_t *ui_lblDate;
extern lv_obj_t *ui_lblTimeLastDecode;
extern lv_obj_t *ui_lblTimeZone;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_imgAntenna;
extern lv_obj_t *ui_barSignalStrength;
extern lv_obj_t *ui_lblPar1;
extern lv_obj_t *ui_lblPar2;
extern lv_obj_t *ui_lblPar3;
extern lv_obj_t *ui_Label1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

